import { Alert, Button, Input, Main } from '@/styles/frontend'
import Head from 'next/head'
import { useState } from 'react'
import axios from 'axios'


export default function Home() {
  const [inputvalue, setInputValue]=useState("")
  const [buttonvalue, setButtonValue]=useState("")
  const [token, setToken]=useState("")

  console.log({inputvalue,buttonvalue})
  const handleChange=(event)=>{
    setInputValue(event.target.value)
  }

  const handleClick=(event)=>{
    setButtonValue(event.target.value)
  }

  
  const handleToken=()=>{
    const consumerKey = process.env.CONSUMER_KEY;
    const consumerSecret = process.env.CONSUMER_SECRET;

    
    const auth = Buffer.from(`${consumerKey}:${consumerSecret}`).toString('base64');
  
    const headers = {
      'Content-Type': 'application/json',
      Authorization: `Basic ${auth}`,
    };
    
    const url = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials';
    
    axios.post(url, null, { headers })
      .then(response => {
        const accessToken = response.data.access_token;
        setToken(accessToken)
      })
      .catch(error => {
        console.error(error);
      });
}  

  const handleSubmit = async (event) => {
    event.preventDefault();

    const tillno=process.env.PASS_KEY
    const secret=process.env.BUSINESS_SHORTCODE
    const time=process.env.TIMESTAMP

    const url = 'https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest';
    const auth = 'Bearer ' + token;
    const headers = { Authorization: auth };
    const passkey=Buffer.from(`${secret}+${tillno}+${time}`)
    const data = {
      BusinessShortCode: process.env.BUSINESS_SHORTCODE,
      Password:passkey,
      Timestamp: process.env.TIMESTAMP,
      TransactionType: 'CustomerPayBillOnline',
      Amount: buttonvalue,
      PartyA: inputvalue,
      PartyB: process.env.BUSINESS_SHORTCODE,
      PhoneNumber: inputvalue,
      CallBackURL: process.env.CALLBACK_URL,
      AccountReference: 'Test payment',
      TransactionDesc: 'Test payment description',
    };

    try {
      const response = await axios.post(url, data, { headers });
      console.log(response.data);
    } catch (error) {
      console.error(error);
    }
  };  

  return (
    <>
      <Head>
        <title>LipaMpesa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Button onClick={handleToken}>Generate Token</Button>
        <Input  placeholder='enter your phone number' value={inputvalue} onChange={handleChange}/>
        <Button value="50"  onClick={handleClick}>transact 50 ksh</Button>
        <Button value="100" onClick={handleClick}>transact 100 ksh</Button>
        <Button value="150" onClick={handleClick}>transact 150 ksh</Button>
        {!buttonvalue?(<div></div>):(
        <>
        <Alert>you are about to send {buttonvalue} ksh, press confirm to continue</Alert>
        <Button onClick={handleSubmit}>Confirm</Button>
        </>
        )}
      </Main>
    </>
  )
}
